services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ..:/var/www1
    depends_on:
      - mailcatcher

  nginx:
    build:
      context: ./nginx
    volumes:
      - ..:/var/www1
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=speechday
      - MYSQL_USER=speechday
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
    depends_on:
      - nginx
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=docker
    restart: always
    links:
      - database

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always

  ldap:
    image: bitnami/openldap
    container_name: speechday_ldap
    ports:
      - "389:389"
      - "1389:1389"
    restart: always
